### PR TITLE
Revamp & port to .netstandard2.1

### PR DESCRIPTION
**Pull request by delneg**
Here's what's done:
- Removed paket & fake - too much work getting them to work properly
- Added github actions - build & tests on .netcore 3.1, .net5.0 and .net 6.0
- Target netstandart 2.1 with the library, net7.0 with benches & netcoreapp3.1 with tests
- Remove Travis & Appveyor - because of Github Actions
- Remove #if MONO flags in Benches
- Fix fsproj files - use new format

### CODE REVIEW

**Comment by delneg** [comment]
cc @jackmott  @marklam

**Comment by dsyme** [comment]
@delneg should we look at making you a maintainer here?

**Comment by dsyme** [comment]
@jackmott let me know if there is an issue with the merge - by policy I should have waited some time before acting as backup maintainer

**Comment by marklam** [comment]
@denelg I can have a go at fixing up the Fake / Paket stuff (from the Project Scaffold) if it's useful for publishing packages & docs or whatever.

**Comment by dsyme** [comment]
If you need it take a look at the automated docs and package publishing here

https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/main/.github/workflows/publish.yml

**Comment by delneg** [comment]
> @delneg should we look at making you a maintainer here?

Hello, thank you for your proposal. However, given the current geopolitical situation I'm not sure that I'm a good fit for it  (and I don't think that it's a good idea that someone might depend on me)

>@denelg I can have a go at fixing up the Fake / Paket stuff (from the Project Scaffold) if it's useful for publishing packages & docs or whatever.


Anyway, regarding Paket and Fake - in my few years of experience they just make thinks harder to work with, unless in specific cases (when you can install nuget from git repo for example with Paket)
But overall I've found that they just bring not always necessary complexity to the package, and for one like this I think everything works just fine with `dotnet build` on all platforms (I've currently tested windows and linux both on x86_64, but can also test on macos x86_64 / arm64 if needed)
> If you need it take a look at the automated docs and package publishing here
> https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/main/.github/workflows/publish.yml


If you decide to fix them it's could be useful, but personally I'd prefer to use the aforementioned github actions used for AsyncSeq for the tasks of publishing packages & docs

**Comment by marklam** [comment]
I've made a PR for the github actions approach, and a couple of tweaks to the project file to populate the package info & set a version (I set it to beta just because the previous published release was beta)

(sorry for mis-spelling your id in the previous comment, @delneg)

**Comment by delneg** [comment]
> I've made a PR for the github actions approach, and a couple of tweaks to the project file to populate the package info & set a version (I set it to beta just because the previous published release was beta)
> 
> (sorry for mis-spelling your id in the previous comment, @delneg)

Thanks ! Looks great , probably only need to swap dotnet 5 for dotnet 6 (as dotnet 6 is LTS and dotnet 5 is EOL)
(no problem regarding misspelling it's not an issue at all)

**Comment by marklam** [comment]
Thanks, added that change to https://github.com/fsprojects/SIMDArray/pull/26

**Pull request merged**
