### PR TITLE
Added tests missing (#14), uncommented benches

### PR DESCRIPTION
**Pull request by delneg**
As per remaining goals in the issue #14 , I've added missing tests.
Also , I've added some benches that were commented previously & added the results to readme
However, Array.mapFoldBack fails for some reason.
I don't actually understand why, maybe because I have a hard time processing what "mapFold" does anyways, let alone "mapFoldBack"
Maybe someone could help out ?
cc @jackmott @marklam @dsyme

### CODE REVIEW

**Comment by dsyme** [comment]
mapFold applies a function along a list, producing a new list, like map.

Along the way, at each step, a state is passed to the function, and a new state returned.

mapFoldBack should do the same thing, but starting from the back of the list/array instead of the front.

**Comment by delneg** [comment]
> mapFold applies a function along a list, producing a new list, like map.
> 
> Along the way, at each step, a state is passed to the function, and a new state returned.
> 
> mapFoldBack should do the same thing, but starting from the back of the list/array instead of the front.

Thanks a lot for the explanation :)
I'll try to understand what's going wrong, as of right now I can't see what's not fitting the description - mapFoldBack looks like inversed mapFold (as it should)

**Comment by marklam** [comment]
Looks like the parameters to the functions passed to mapFoldBack should be the other way round to mapFold:
```diff
 [<Test>]                  
 let ``SIMD.mapFoldBack = Array.mapFoldBack`` () =
     quickCheck <|
     fun (xs: int []) ->
         (xs.Length > 0 && xs <> [||]) ==>
-        let inline funcIntMul acc x = x*x, acc + x
-        let inline funcIntMinus acc x = x-x, acc-x
+        let inline funcIntMul x acc = x*x, acc + x
+        let inline funcIntMinus x acc = x-x, acc-x
```

~~But that's not enough to fix it.... I'll keep looking.~~ Checked it again, that seems to work.

I think it does mean that the values of the state passed in at each stage must differ from `Array.mapFoldBack` though.

**Comment by delneg** [comment]
> 
Screenshot 2022-05-20 at 16 39 11

Well, looks like it fixed it for me

**Comment by marklam** [comment]
You're right. I had a moment of doubt, but it does seem to fix it.

The state/accumulator works differently to `Array.mapFold` and `Array.mapFoldBack`, which can be seen if it's used in the map function:
```F#
        let inline funcIntMul acc x = x*x+acc, acc + x
```
But since the SIMD version isn't a drop-in replacement anyway, I'm not sure it's a problem. I don't think it's possible to exactly match the `Array` function behaviour..

**Comment by delneg** [comment]
@dsyme  Sorry for bothering you, I just don't know if anyone else has merge rights for the repo - anyway this PR is ready for merging.

**Comment by dsyme** [comment]
I've invited you both to have access, as I believe that's appropriate

**Comment by marklam** [comment]
Thanks @dsyme, I'll go ahead and merge this then.

**Comment by delneg** [comment]
Thanks, I've accepted the invitation also, great

**Pull request merged**
